server:
  port: 8086
spring:
  profiles:
    active: dev
  application:
    name: survey-service
  datasource:
    url: jdbc:h2:mem:mydb
    username: anc
    password: pwd
    driverClassName: org.h2.Driver
  jpa:
   database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/